#!/bin/sh
# The certificates the TLS tests use, made once and checked in.
#
# A test certificate authority, and what it signed: a server certificate for
# `localhost` and 127.0.0.1, one that expired long ago, one the authority has
# revoked -- with the CRL that says so, and the OCSP responses a server would
# staple for it and for the good one -- and a client certificate for mutual
# TLS. A second, unrelated authority stands in for "a CA
# nobody here trusts". Identities are PKCS#12 bundles, password `dream`,
# because that is the format every backend imports (see dream/src/tls.hpp);
# they are encrypted with 3DES and a SHA-1 MAC, the one combination every
# Windows that SChannel runs on can open. Nothing here protects anything: these
# keys are public by being in this repository, and are good for nothing but
# these tests.
#
# Run it again only to change what the tests need. It writes the files beside
# it, and `tls_fixtures.hpp`, the same files as C++ for the VM's own tests.
set -eu
cd "$(dirname "$0")"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# RSA rather than EC: it is the key every SChannel and every crypt32 imports,
# Wine's included, which is where the Windows backend can be run off Windows.
key() { openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$1" 2>/dev/null; }

authority() {  # key cert cn
    key "$1"
    openssl req -x509 -key "$1" -out "$2" -days 36500 -subj "/CN=$3" \
        -addext "basicConstraints=critical,CA:TRUE" \
        -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null
}

authority "$work/ca.key" ca.pem "Dream Test CA"
authority "$work/other.key" other_ca.pem "Some Other CA"

# `openssl ca`, rather than `x509 -req`, because it takes a start date: the
# expired certificate has to have been valid once, long ago.
mkdir -p "$work/db"
: > "$work/db/index.txt"
echo 1000 > "$work/db/serial"
echo 1000 > "$work/db/crlnumber"
cat > "$work/ca.cnf" <<CNF
[ca]
default_ca = test
[test]
database = $work/db/index.txt
serial = $work/db/serial
crlnumber = $work/db/crlnumber
default_crl_days = 36500
new_certs_dir = $work/db
certificate = ca.pem
private_key = $work/ca.key
default_md = sha256
policy = anything
unique_subject = no
copy_extensions = none
[anything]
commonName = supplied
[server]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost,IP:127.0.0.1
[client]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = clientAuth
subjectAltName = DNS:client.test
CNF

leaf() {  # name cn section start end
    key "$work/$1.key"
    openssl req -new -key "$work/$1.key" -subj "/CN=$2" -out "$work/$1.csr" 2>/dev/null
    openssl ca -batch -config "$work/ca.cnf" -extensions "$3" -startdate "$4" -enddate "$5" \
        -in "$work/$1.csr" -out "$work/$1.pem" -notext 2>/dev/null
    openssl pkcs12 -export -inkey "$work/$1.key" -in "$work/$1.pem" -certfile ca.pem -name "$1" \
        -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -macalg sha1 -passout pass:dream -out "$1.p12"
}

leaf server localhost server 20260101000000Z 21260101000000Z
leaf expired localhost server 20000101000000Z 20010101000000Z
leaf client "Dream Test Client" client 20260101000000Z 21260101000000Z
leaf revoked localhost server 20260101000000Z 21260101000000Z

# Revoke the one, and publish the list that says so.
openssl ca -batch -config "$work/ca.cnf" -revoke "$work/revoked.pem" -crl_reason keyCompromise 2>/dev/null
openssl ca -batch -config "$work/ca.cnf" -gencrl -out ca.crl 2>/dev/null

# What an OCSP responder -- the authority itself, here -- says of each server
# certificate, as `s_server -status_file` staples it.
ocsp() {  # name
    openssl ocsp -issuer ca.pem -cert "$work/$1.pem" -no_nonce -reqout "$work/$1.req" 2>/dev/null
    openssl ocsp -index "$work/db/index.txt" -rsigner ca.pem -rkey "$work/ca.key" -CA ca.pem \
        -reqin "$work/$1.req" -respout "$1.ocsp" -ndays 36500 2>/dev/null
}
ocsp server
ocsp revoked

# For `openssl s_server`, which the end-to-end test talks to.
cat "$work/server.pem" ca.pem > server.pem
cp "$work/server.key" server.key
cat "$work/revoked.pem" ca.pem > revoked.pem
cp "$work/revoked.key" revoked.key

{
    echo "// Generated by make_fixtures.sh from the files beside it. Do not edit."
    echo "#pragma once"
    echo "#include <string>"
    echo "namespace tls_fixtures {"
    for f in ca.pem other_ca.pem ca.crl server.p12 expired.p12 revoked.p12 client.p12; do
        id=$(echo "$f" | tr . _)
        printf 'static const unsigned char %s_bytes[] = {' "$id"
        od -An -v -tu1 "$f" | tr -s ' \n' ',' | sed 's/^,//; s/,$//'
        printf '};\n'
        printf 'inline std::string %s() { return std::string(reinterpret_cast<const char*>(%s_bytes), sizeof %s_bytes); }\n' "$id" "$id" "$id"
    done
    echo 'inline const char* password = "dream";'
    echo "}  // namespace tls_fixtures"
} > tls_fixtures.hpp
