#!/usr/bin/env bash
# Build a self-contained interpreter library and CLI with the Android NDK.
# Dependency sources are supplied by the caller; no downloads happen here.
set -euo pipefail
if [[ $# != 4 ]]; then
    echo "usage: ANDROID_NDK_ROOT=... $0 arm64-v8a|x86_64 OUTPUT LIBFFI_SOURCE OPENSSL_SOURCE" >&2
    exit 2
fi
abi=$1
mkdir -p "$2"
out=$(cd "$2" && pwd)
ffi=$(cd "$3" && pwd)
ssl=$(cd "$4" && pwd)
root=$(cd "$(dirname "$0")/../.." && pwd)
: "${ANDROID_NDK_ROOT:?Set ANDROID_NDK_ROOT to an NDK r28 or newer}"
export ANDROID_NDK_ROOT
case $(uname -s) in
    Linux) host=linux-x86_64 ;;
    Darwin) host=darwin-x86_64 ;;
    *) echo "Build on Linux or macOS" >&2; exit 2 ;;
esac
case $abi in
    arm64-v8a) triple=aarch64-linux-android; openssl_target=android-arm64 ;;
    x86_64) triple=x86_64-linux-android; openssl_target=android-x86_64 ;;
    *) echo "Unsupported Android ABI: $abi" >&2; exit 2 ;;
esac
api=34
jobs=${JOBS:-2}
export PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/$host/bin:$PATH"
prefix="$out/deps"
mkdir -p "$out/ffi" "$out/openssl"
(
    cd "$out/ffi"
    CC="$triple$api-clang" CXX="$triple$api-clang++" AR=llvm-ar RANLIB=llvm-ranlib \
        "$ffi/configure" --host="$triple" --prefix="$prefix" \
        --disable-shared --enable-static --with-pic --disable-docs
    make -j"$jobs"
    make install
)
(
    cd "$out/openssl"
    "$ssl/Configure" "$openssl_target" -D__ANDROID_API__=$api \
        --prefix="$prefix" --libdir=lib no-shared no-tests no-module
    make -j"$jobs"
    make install_sw
)
cmake -S "$root" -B "$out/vm" \
    -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI="$abi" -DANDROID_PLATFORM="android-$api" \
    -DANDROID_STL=c++_shared -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
    -DCMAKE_BUILD_TYPE=Release -DDREAM_ENABLE_JIT=OFF -DDREAM_LINK_DEPS=STATIC \
    -DDREAM_FFI_INCLUDE="$prefix/include" -DDREAM_FFI_LIB="$prefix/lib/libffi.a" \
    -DOPENSSL_INCLUDE_DIR="$prefix/include" \
    -DOPENSSL_SSL_LIBRARY="$prefix/lib/libssl.a" \
    -DOPENSSL_CRYPTO_LIBRARY="$prefix/lib/libcrypto.a"
cmake --build "$out/vm" --parallel "$jobs"
mkdir -p "$out/dist"
cp "$out/vm/bin/dream" "$out/vm/bin/dream_tests" "$out/dist/"
# Android's loader uses the unversioned SONAME generated by CMake.
cp -L "$out/vm/lib/libdream.so" "$out/dist/"
cp "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/$host/sysroot/usr/lib/$triple/libc++_shared.so" "$out/dist/"
