std:="./std"
src := "tool/main.dr"
output := "mind.dream"
dream := "../build-dream/bin/dream"
compiler := "../build/dreams.dream"

clean:
   rm -f $(output) 
build:
    $(dream) $(compiler) -L {{std}} -o {{output}} {{src}}
selfbuild:
    dream mind.dream
run:
    dream $(output)    
rebuild: build run