std:="./std"
src := "tool/main.dr"
output := "mind.dream"

clean:
   rm -f $(output) 
build:
    dreamc -L {{std}} -o {{output}} {{src}}
selfbuild:
    dream mind.dream
run:
    dream $(output)    
rebuild: build run